name: "Check shell"

on:
  pull_request_target:

permissions: {}

jobs:
  x86_64-linux:
    name: shell-check-x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          # pull_request_target checks out the base branch by default
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31.3.0
      - name: Build shell
        run: nix-build shell.nix

  aarch64-darwin:
    name: shell-check-aarch64-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          # pull_request_target checks out the base branch by default
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31.3.0
      - name: Build shell
        run: nix-build shell.nix
