name: "Building Nixpkgs lib-tests"

on:
  pull_request:
    paths:
      - .github/workflows/lib-tests.yml
  pull_request_target:
    paths:
      - 'lib/**'
      - 'maintainers/**'

permissions: {}

jobs:
  nixpkgs-lib-tests:
    name: nixpkgs-lib-tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .github/actions
      - name: Check if the PR can be merged and get the test merge commit
        uses: ./.github/actions/get-merge-commit
        id: get-merge-commit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ steps.get-merge-commit.outputs.mergedSha }}

      - uses: cachix/install-nix-action@17fe5fb4a23ad6cbbe47d6b3f359611ad276644c # v31
        with:
          extra_nix_config: sandbox = true

      - name: Building Nixpkgs lib-tests
        run: |
          nix-build ci -A lib-tests
